initialize: workaround fatal: the remote end hung up unexpectedly
This patch is a workaround to failing to clone and fech the linuxpcc-dev
public inbox.  Turns out it somehow does not like the separate git clone
+ git fetch that notmuch-lore does, but a plain shallow clone --since
works!

Since this error meessage is somewhat common with the http backend, I
tried first by extending the http.postBuffer after the clone step but
before fetch:

   git --git-dir=$gitdir/$epoch config http.postBuffer 524288000

This did not help, despite the linuxpcc-dev mailing list being one big
epoch, and enabling curl debug did not show anything more interesting
than the above error message (and lots of http post of course):

   export GIT_TRACE_PACKET=1
   export GIT_TRACE=1
   export GIT_CURL_VERBOSE=1

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/pre-new b/pre-new
--- a/pre-new
+++ b/pre-new
@@ -85,8 +85,17 @@ initialize()
 	echo "  epoch$epoch: initial import" >&2
 	if ! git --git-dir=$gitdir/$epoch fetch --quiet \
 	     --shallow-since="$since" 2>/dev/null; then
-	    echo "    no messages in range." >&2
-	    continue
+	    if [ $epoch -eq 0 ]; then
+		# retry without separate git fetch, e.g. linuxppc-dev
+		rm -rf "${gitdir:?}/$epoch"
+		if ! git clone --mirror --shallow-since="$since" "$url/0" "$gitdir/0"; then
+		    echo "    failed cloning repo $url"
+		    continue
+		fi
+	    else
+		echo "    no messages in range." >&2
+		continue
+	    fi
 	fi
 
 	import $1 $gitdir/$epoch master
